"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Noah Wood and Luis Higareda, this 
programming assignment is my own work and I have not provided this code to 
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: nww376
UT EID 2: leh3479
"""


def length_of_longest_substring_n3(s):
    """
    Finds the length of the longest substring without repeating characters
    using a brute force approach (O(N^3)).

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    ascii_freq = [False] * 256
    list_char = []
    temp_freq = 0
    max_freq = 0
    for i in range(len(s)):
        for j in range(i + 1, len(s)):
            list_char.append(s[i:j+1])
    for characters in list_char:
        length = len(characters)
        for char_index in range(length):
            if ascii_freq[ord(characters[char_index])] is False:
                ascii_freq[ord(characters[char_index])] = True
                temp_freq += 1
            else:
                max_freq = max(max_freq,temp_freq)
                temp_freq = 0
        max_freq = max(max_freq,temp_freq)
        temp_freq = 0
        ascii_freq = [False] * 256
    return max_freq



def length_of_longest_substring_n2(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N^2)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """

    max_len = 0
    length = len(s)
    for index in range(length):
        rep_ascii = [False] * 256
        rep_ascii[ord(s[index])] = True
        temp = 1
        tracker = True
        for next_let in range(index + 1, length):
            if tracker is True:
                if rep_ascii[ord(s[next_let])] is False:
                    temp += 1
                    rep_ascii[ord(s[next_let])] = True
                else:
                    tracker = False
        max_len = max(max_len, temp)
    return max_len

def length_of_longest_substring_n(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list. However, this approach stops early, breaking out of the inner
    loop when a repeating character is found. You may also choose to challenge
    yourself by implementing a sliding window approach.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    max_len = 0
    length = len(s)
    for index in range(length):
        rep_ascii = [False] * 256
        rep_ascii[ord(s[index])] = True
        temp = 1
        for next_let in range(index + 1, length):
            if rep_ascii[ord(s[next_let])] is True:
                break
            temp += 1
            rep_ascii[ord(s[next_let])] = True
        max_len = max(max_len, temp)
    return max_len
